# Generated by Django 6.1.1 on 2026-09-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What uses this token, e.g. 'home-assistant'.",
                        max_length=100,
                    ),
                ),
                (
                    "key_id",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("key_hash", models.CharField(editable=False, max_length=64)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read only (GET, HEAD, OPTIONS)"),
                            ("write", "Read and write"),
                        ],
                        default="read",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user", "name"),
                        name="api_tokens_unique_active_name_per_user",
                    )
                ],
            },
        ),
    ]
